#ifndef __eeprom_h_
#define __eeprom_h_


#define EEPROM_QUEUE_SIZE 32
#define EEPROM_QUEUE_INDEX_MASK EEPROM_QUEUE_SIZE - 1;
unsigned char EEPROM_read(unsigned int address);
unsigned char EEPROM_prep(unsigned int address, unsigned char data);
void EEPROM_write(void);


#define BASE_BOX_EEPROM_LOW_BYTE		128
#define BASE_BOX_EEPROM_HIGH_BYTE	    129	
#define BASE_FLOOR_EEPROM_LOW_BYTE		130
#define BASE_FLOOR_EEPROM_HIGH_BYTE		131
#define BASE_LOW_EEPROM_LOW_BYTE		132
#define BASE_LOW_EEPROM_HIGH_BYTE		133	
#define BASE_MIDDLE_EEPROM_LOW_BYTE		134
#define BASE_MIDDLE_EEPROM_HIGH_BYTE	135	
#define BASE_HIGH_EEPROM_LOW_BYTE		136
#define BASE_HIGH_EEPROM_HIGH_BYTE		137
#define ELBOW_BOX_EEPROM_LOW_BYTE		138
#define ELBOW_BOX_EEPROM_HIGH_BYTE		139
#define ELBOW_FLOOR_EEPROM_LOW_BYTE		140
#define ELBOW_FLOOR_EEPROM_HIGH_BYTE	141
#define ELBOW_LOW_EEPROM_LOW_BYTE		142
#define ELBOW_LOW_EEPROM_HIGH_BYTE		143
#define ELBOW_MIDDLE_EEPROM_LOW_BYTE	144
#define ELBOW_MIDDLE_EEPROM_HIGH_BYTE	145
#define ELBOW_HIGH_EEPROM_LOW_BYTE		146
#define ELBOW_HIGH_EEPROM_HIGH_BYTE		147
#define WRIST_BOX_EEPROM_LOW_BYTE		148
#define WRIST_BOX_EEPROM_HIGH_BYTE		149
#define WRIST_FLOOR_EEPROM_LOW_BYTE		150
#define WRIST_FLOOR_EEPROM_HIGH_BYTE	151	
#define WRIST_LOW_EEPROM_LOW_BYTE		152
#define WRIST_LOW_EEPROM_HIGH_BYTE		153
#define WRIST_MIDDLE_EEPROM_LOW_BYTE	154
#define WRIST_MIDDLE_EEPROM_HIGH_BYTE	155	
#define WRIST_HIGH_EEPROM_LOW_BYTE		156
#define WRIST_HIGH_EEPROM_HIGH_BYTE		157
#define GRIPPER_OPEN_EEPROM_LOW_BYTE	158
#define GRIPPER_OPEN_EEPROM_HIGH_BYTE	159	
#define GRIPPER_CLOSED_EEPROM_LOW_BYTE	160
#define GRIPPER_CLOSED_EEPROM_HIGH_BYTE	161		


#endif
